# Generated by Django 4.0.6 on 2022-07-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='materia',
            new_name='materias',
        ),
    ]
