# Generated by Django 4.0.6 on 2022-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='nota',
            field=models.FloatField(blank=True, max_length=25, null=True),
        ),
    ]
